
import { Link } from "react-router-dom";
import { ArrowLeft, FileText, ExternalLink, ChevronDown, ChevronUp } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { useState } from "react";

const Research = () => {
  return (
    <div className="bg-white text-gray-800 min-h-screen">
      <div className="max-w-5xl mx-auto p-6">
        <div className="mb-6">
          <Link to="/" className="inline-flex items-center text-blue-600 hover:text-blue-800">
            <ArrowLeft size={16} className="mr-2" />
            Back to Home
          </Link>
        </div>
        
        <h1 className="text-3xl font-bold mb-6">Research</h1>
        
        <p className="text-gray-700 mb-8 text-lg">
          My research is dedicated to advancing the real-world application of artificial intelligence, with a focus on developing scalable, robust, and high-impact intelligent systems. By integrating machine learning, and data-driven modeling, I aim to address complex, uncertain challenges and drive the adoption of AI across different sectors.
        </p>
        
        <ResearchArea
          id="llm-decision-support"
          title="LLM-Enhanced Decision Support System"
          image="/lovable-uploads/16c97d0e-ae76-4f4d-a7bb-402f6ac84038.png"
          description="SR Mailing Ltd is a pioneering company in the sustainable packaging industry. In this project, we will lead the integration of cutting-edge Artificial Intelligence (AI) and Large Language Model (LLM) techniques into SR Mailing's systems. The collaboration aims to develop LLM-enhanced data analytics, customer relationship management, and operational optimisation to support sustainable practices. This integration is expected to enhance decision-making across management, marketing, and sales, drive market expansion, and position SR Mailing as a sector leader in AI-enhanced decision support. The project is funded by Innovate UK and SR Mailing Ltd."
          keyPublications={[]}
          fundingInfo="2025 - 2027, Principal Investigator, £338,916, 'LLM-enhanced decision support system for the sustainable packaging sector', Knowledge Transfer Partnerships with SR Mailing, Innovate UK"
        />
        
        <ResearchArea
          id="neural-architecture"
          title="Neural Architecture Search"
          image="/lovable-uploads/dd5e9ded-1792-45fc-ab75-91681764dd61.png"
          description="We investigate automated methods to discover efficient neural network architectures tailored for specific computer vision tasks. Our research addresses the challenge of designing architectures that balance computational requirements, memory footprint, and task performance."
          keyPublications={[
            {
              title: "Neural Architecture Search for Efficient Deep Learning Models",
              authors: "Jane Researcher, David Johnson, Maria Garcia",
              venue: "International Conference on Machine Learning (ICML), 2022",
              link: "/publications"
            }
          ]}
        />
        
        <ResearchArea
          id="adversarial-robustness"
          title="Adversarial Robustness"
          image="https://picsum.photos/id/1024/800/400"
          description="This research direction focuses on improving the robustness of computer vision models against adversarial attacks and natural corruptions. We develop training methodologies and architectural innovations to create models that maintain high performance even in the presence of input perturbations."
          keyPublications={[
            {
              title: "Adversarial Training Methods for Robust Visual Perception",
              authors: "Jane Researcher, Robert Brown",
              venue: "Neural Information Processing Systems (NeurIPS), 2022",
              link: "/publications"
            }
          ]}
        />
        
        <ResearchArea
          id="game-generation"
          title="Learning-Based Game Generation"
          image="/lovable-uploads/bb3e3142-0626-4c45-ae1e-36a26deb2c7a.png"
          description="This research project aims to develop a novel procedural content generation method to create high-quality levels in Super Mario Bros. To achieve this, we propose a hybrid approach that leverages the synergy between rule-based and learning-based methods to produce constructive primitives—high-quality yet controllable game segments in Super Mario Bros. These primitives can be adopted as the basic building blocks of a game level and enable online level generation and real-time content adaptation based on various design criteria. Examples of levels generated by our approach are shown above."
          keyPublications={[
            {
              title: "Learning constructive primitives for real-time dynamic difficulty adjustment in Super Mario Bros",
              authors: "P. Shi, and K. Chen",
              venue: "IEEE Transactions on Games, 2017",
              link: "/publications"
            },
            {
              title: "Online level generation in Super Mario Bros via learning constructive primitives",
              authors: "P. Shi, and K. Chen",
              venue: "IEEE Conference on Computational Intelligence and Games, 2016",
              link: "/publications"
            }
          ]}
        />
        
        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4 border-b pb-2" id="grant">Grant</h2>
          <ul className="space-y-4">
            <li>
              <p className="text-gray-700"><strong>2025 - 2027</strong>, Principal Investigator, £338,916, "LLM-enhanced decision support system for the sustainable packaging sector", Knowledge Transfer Partnerships with SR Mailing, Innovate UK</p>
            </li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4 border-b pb-2" id="invited-talks">Invited talk</h2>
          <ul className="space-y-4">
            <li>
              <p className="text-gray-700"><strong>2025</strong>, "LLM-Enhanced Decision Support System for the Sustainable Packaging Sector", co-presented with Kun Feng (Director of SR Mailing) at the ATOD event, University of Leeds</p>
            </li>
            <li>
              <p className="text-gray-700"><strong>2025</strong>, "Applying AI for Enterprise Intelligence and Manufacturing Innovation", The Future Advanced Metrology Hub for Sustainable Manufacturing</p>
            </li>
            <li>
              <p className="text-gray-700"><strong>2023</strong>, "Machine Learning for Decision-making in Intelligent Manufacturing", centre for decision research, University of Leeds</p>
            </li>
            <li>
              <p className="text-gray-700"><strong>2023</strong>, "Machine Learning Research in Intelligent Manufacturing", research festival, University of Huddersfield</p>
            </li>
            <li>
              <p className="text-gray-700"><strong>2019</strong>, "Machine Learning and its Applications", EPSRC Future Advanced Metrology Hub</p>
            </li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4 border-b pb-2" id="journal-reviewer">Journal reviewer</h2>
          <ul className="space-y-2">
            <li><p className="text-gray-700">IEEE Transactions on Industrial Informatics</p></li>
            <li><p className="text-gray-700">Robotics and Computer-integrated Manufacturing</p></li>
            <li><p className="text-gray-700">Artificial Intelligence Review</p></li>
            <li><p className="text-gray-700">Journal of Intelligent Manufacturing</p></li>
            <li><p className="text-gray-700">CIRP Annals - Manufacturing Technology</p></li>
            <li><p className="text-gray-700">IEEE Transactions on Games</p></li>
            <li><p className="text-gray-700">Journal of Business Analytics</p></li>
            <li><p className="text-gray-700">Journal of the Operational Research Society</p></li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4 border-b pb-2" id="guest-editor">Guest editor</h2>
          <ul className="space-y-2">
            <li><p className="text-gray-700">Special Issue "Application of Artificial Intelligence Techniques in Additive Manufacturing" of Processes.</p></li>
          </ul>
        </section>
        
      </div>
    </div>
  );
};

interface ResearchAreaProps {
  id: string;
  title: string;
  image: string;
  description: string;
  keyPublications: {
    title: string;
    authors: string;
    venue: string;
    link: string;
  }[];
  fundingInfo?: string;
}

const ResearchArea: React.FC<ResearchAreaProps> = ({
  id,
  title,
  image,
  description,
  keyPublications,
  fundingInfo
}) => {
  const [expanded, setExpanded] = useState(false);
  
  return (
    <section className="mb-12" id={id}>
      <h2 className="text-2xl font-bold mb-4 border-b pb-2">{title}</h2>
      <div className="mb-4 overflow-hidden rounded-lg">
        <img 
          src={image} 
          alt={title}
          className="w-full h-auto"
        />
      </div>
      <p className="text-gray-700 mb-4">{description}</p>
      
      <div>
        <button 
          onClick={() => setExpanded(!expanded)}
          className="flex items-center text-blue-600 hover:text-blue-800 mb-2"
        >
          {expanded ? (
            <>
              <ChevronUp size={16} className="mr-1" />
              {fundingInfo ? "Hide Funding Information" : "Hide Key Publications"}
            </>
          ) : (
            <>
              <ChevronDown size={16} className="mr-1" />
              {fundingInfo ? "Show Funding Information" : "Show Key Publications"}
            </>
          )}
        </button>
        
        {expanded && (
          <div className="pl-4 border-l-2 border-blue-200 mb-4">
            {fundingInfo ? (
              <>
                <h3 className="font-medium mb-2">Funding Information</h3>
                <p className="text-gray-700">{fundingInfo}</p>
              </>
            ) : (
              <>
                <h3 className="font-medium mb-2">Key Publications</h3>
                <ul className="space-y-3">
                  {keyPublications.map((pub, index) => (
                    <li key={index}>
                      <p className="font-medium">{pub.title}</p>
                      <p className="text-gray-700 text-sm">{pub.authors}</p>
                      <p className="text-gray-600 text-sm italic">{pub.venue}</p>
                      <Link to={pub.link} className="text-blue-600 hover:text-blue-800 text-sm">
                        View Publication
                      </Link>
                    </li>
                  ))}
                </ul>
              </>
            )}
          </div>
        )}
      </div>
    </section>
  );
};

export default Research;
